### ISSUE TITLE
代码跑起来和在线访问的demo不一样

### ISSUE THREAD

**Issue by liuyingqq123** [g0ngjie/antv-x6-vue2#1]
代码跑起来和在线访问的demo不一样, 控制台报了很多错, 上面一行的控制栏也没有

**Comment by Nyakooo** [comment]
Demo是项目打包放到 GitHub pages上面，应该不存在不一样的情况。
可能是部分依赖没有安装成功。
可以参考一下我的环境：Node v16.16.0、Pnpm v7.27.0

**Comment by YanWaite** [comment]
使用pnpm进行依赖安装,就不会出现控制台报错问题

**Comment by YanWaite** [comment]
还有一个问题, 这个不是vue3的项目吗? 不是vue2的 XD

**Comment by YanWaite** [comment]
还有一个问题, 这个项目标题不是vue2的项目吗? 代码是vue3的 XD

**Comment by Nyakooo** [comment]
> 还有一个问题, 这个项目标题不是vue2的项目吗? 代码是vue3的 XD

vue2的

**Comment by YanWaite** [comment]
> 

不是喔, setup函数,toRefs,reactive函数,这些是vue3的内容喔, vue2使用的是data函数的
