### ISSUE TITLE
可以提供一个关于左边拖拽栏的自定义选项吗

### ISSUE THREAD

**Issue by nanfb** [g0ngjie/antv-x6-vue2#2]
给定一个对象，里面有自定义的svg图像，还有就是line的选择，北京颜色的自定义，背景点的ture和false，这个库可拓展性太差了，要不写个纯vue页面的项目，我可以自己修改，谢谢

**Comment by Nyakooo** [comment]
这个项目是当年工作所需研发的。现在已经废弃SVG全部采用Vue形式开发了。涉及到公司安全层面问题，庞杂的组件元素导致无法完全抽离成一个Demo，以后有时间我会再整理一版。

**Comment by nanfb** [comment]
> 这个当年工作所研发的的现在现在现在已经已经全部全部全部全部全部采用全部全部形式形式形式形式形式形式开发开发了了了。涉及涉及涉及涉及到到到公司安全层面层面到公司层面层面问题涉及到安全层面。

好吧，你们现在还是基于antd x6开发的吗？废弃svg不太可能吧，全部用dom操作实现吗？自定义的节点怎么实现的呢😊

**Comment by Nyakooo** [comment]
目前现在业务场景复杂，所以全部采用Vue组件形式注入。用这个包(**@antv/x6-vue-shape@1.4.0**)
