### ISSUE TITLE
可以问下这个库中有有用到自定义组件吗

### ISSUE THREAD

**Issue by nanfb** [g0ngjie/antv-x6-vue2#3]
基于path的自定义组件的大小是不能通过size()修改的，通过transform修改，大佬有没有什么办法呢？基于vue的组件中写svg-path也是不行，只能自己算吗？

**Comment by Nyakooo** [comment]
这个库只是以前的一个小Demo，自定义组件没有太多使用。如果要用的话，node.setSize改变的是x6图形的大小，但实际的Dom元素是需要自己动态改变的。
你如果使用了**框选线**的话，你就会发现它的size确实被改变了。

**Comment by nanfb** [comment]
> 这个库只是之前的一个小Demo，自定义组件没有太多使用。如果要用的话，node.setSize改变的是x6图形的大的小，但实际上你的Dom元素児需要自刎。果使用 了**框选择线**的话，你就会发现它的大小确实被改变了。

是的，我刚开始用的是框选，框选打开后发现大小是被改变了的，但是元素没有改，但是我看shape定义的命名空间里有path，而且只有path不行，其他的节点都是可以的，不知道什么原因，自己算可太恶心了，哎~

**Comment by Nyakooo** [comment]
深有体会，后来我全部用Vue组件形式去开发的。灵活度会高很多，尽量不要混用，可能会导致其他问题

**Comment by nanfb** [comment]
> 深有体会，以后我全部用Vue组件式去开发的。灵活度会高很多，尽管量不要混用，可能会导致其他问题

混用的话导出会出问题，两种不同的导出方法，更难受，使用vue渲染的话对于复杂图形使用dom不一定可以绘制出来，就很恶心。我还尝试过在vue里面渲染svg，也是不行，哈哈

**Comment by Nyakooo** [comment]
可能还要注意一下x6的某些版本，元素量较大会导致页面卡死现象。可以尝试切换一下不同版本尝试

**Comment by nanfb** [comment]
> 可能还要注意一下x6的某些版本，元素量较大会导致页面卡死现象。可以尝试切换一下不同版本尝试

2版本以上对于dnd是单独的一个插件，还得重构一些代码，我们的项目是 基于vue2的，太难了，大佬你知道除了antv x6还有什么解决方案吗

**Comment by Nyakooo** [comment]
如果是vue2的话，可能x6已经是一个不错的选择了。如果是vue3的话，可以考虑 [vue-flow](https://vueflow.dev/)

**Comment by nanfb** [comment]
> 如果是vue2的话，可能x6已经是一个不错的选择了。如果是vue3的话，可以考虑 [vue-flow](https://vueflow.dev/)

他们的首页做的好吉尔炫酷，很向pad使用触控笔的那种，吸附

**Comment by Nyakooo** [comment]
那种我也见过，不过这种项目一般都是沉淀了好多年的。像 [scratch-gui](https://llk.github.io/scratch-gui/master/)

**Comment by nanfb** [comment]
> 那种我也见过，不过这种项目一般都是沉淀了好多年的。像 [scratch-gui](https://llk.github.io/scratch-gui/master/)
看着好牛，哎，难搞，
