### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by nanfb** [g0ngjie/antv-x6-vue2#4]
作者有了解过svg的缩略图功能吗？类似于x6那种的，有什么库可以使用呢？

**Comment by Nyakooo** [comment]
抱歉，缩略图方面如果是实现方式的话，确实了解不多。
类似带有缩略图功能的图形化库有很多。
Antv系列的，或者[vue flow](https://vueflow.dev/)、[react flow](https://reactflow.dev/)都是开源的项目，希望能够对你有帮助

**Comment by nanfb** [comment]
> 抱紧，缩小图表方面如果是现实方式的话，确实了解的不多。 类似具有缩小图表功能的图表化库有很多。 Antv系列的，或者[vue flow](https://vueflow.dev/)、[react flow](https://reactflow.dev/)都是开源的项目，希望能对你有帮助

好吧，谢谢
