### ISSUE TITLE
otherParams 参数源自哪里呢

### ISSUE THREAD

**Issue by zw-store** [g0ngjie/antv-x6-vue2#5]
![code](https://github.com/g0ngjie/antv-x6-vue2/assets/53395110/013bc346-d393-4cce-84b1-28babe89b76c)
代码写的很棒，我仔细看了代码。上述图片是一个不源自哪里的对象，项目中没用到。全局搜索了一下是不存在的。
我本地调试代码用的node:14.21.3。出现过依赖不符等情况，调整过依赖有3个【"@antv/x6-vue-shape": "^1.5.4","vue-template-compiler": "^2.6.14","vue": "^2.6.14"】。
建议项目把eslint加上。以下是我调试的依赖相关代码
![code](https://github.com/g0ngjie/antv-x6-vue2/assets/53395110/5be1a0f2-a65d-46ae-b798-5c3c62b27ddc)

**Comment by Nyakooo** [comment]
非常感谢。这个项目时间有点久了，之前为了做调研写的用例。也方便其他人参考使用。
otherParams这个是用对象解构获取剩余的参数，只在当前作用域，所以其他地方是没有的。
